#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
    my ($type, $name, $args) = @_;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

# קריאות מערכת רגילות
entry("int", "fork", "");
entry("int", "exit", "");
entry("int", "wait", "");
entry("int", "pipe", "");
entry("int", "read", "");
entry("int", "write", "");
entry("int", "close", "");
entry("int", "kill", "");
entry("int", "exec", "");
entry("int", "open", "");
entry("int", "mknod", "");
entry("int", "unlink", "");
entry("int", "fstat", "");
entry("int", "link", "");
entry("int", "mkdir", "");
entry("int", "chdir", "");
entry("int", "dup", "");
entry("int", "getpid", "");
entry("int", "sbrk", "");
entry("int", "sleep", "");
entry("int", "uptime", "");

# קריאות מערכת לפיטרסון
entry("int", "peterson_create", "");
entry("int", "peterson_acquire", "int, int");
entry("int", "peterson_release", "int, int");
entry("int", "peterson_destroy", "int");
